name: Sell
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
main: SellHand\Main
version: 1.2.13
author: [Muqsit]
authors: [KairusDarkSeeker, JackMD]
depend: EconomyAPI
commands:
  sell:
    description: "sell items"
    permission: sell.command
permissions:
  sell:
    default: op
    children:
      sell.hand:
        default: op
      sell.all:
        default: op
      sell.command:
        default: true
